### ISSUE TITLE
TypeError: integer argument expected, got float

### ISSUE THREAD

**Issue by polymeric** [tryexceptpass/perceptio#1]
- Pip installed requirements file. 
- Fed several txt files at the app and receive the following:

(env)[polymeric: perceptio (master)]$ python ./visualize.py sample.txt --np-fullcolor
Traceback (most recent call last):
  File "./visualize.py", line 100, in <module>
    npfullcolor(ARGS['<filename>'])
  File "./visualize.py", line 28, in npfullcolor
    img = Image.new('RGB', (side, side), "black")
  File "/Users/polymeric/code/perceptio/env/lib/python2.7/site-packages/PIL/Image.py", line 2050, in new
    return Image()._new(core.fill(mode, size, color))
TypeError: integer argument expected, got float

Python version: 2.7.10
Darwin Kernel Version 14.4.0

**Comment by tryexceptpass** [comment]
It seems I forgot to mention in the readme that python 3 is required. So please retry with that and let me know if you still see the problem

**Comment by polymeric** [comment]
Works in py3. Sorry for the delay.
